### ISSUE TITLE
Notification not clearing for forum theads and blank notifications

### ISSUE THREAD

**Issue by vfowler** [sbrajesh/bp-group-activities-notifier#1]
Using BuddyPress 1.6.x (not with bbPress yet) and some forum notifications are not clearing after clicking on them. They navigate to the correct thread but do not remove the notification. 

I also notice a couple of blank notifications that I can't clear.

Any ideas?

**Comment by code-helps** [comment]
am facing the same problem.. any suggestion.... The group forum activity notification does not clear even after reading if....

Need your support

**Comment by res1l1ence** [comment]
Same here. Blank notifications when one activity is deleted. @sbrajesh

**Comment by TomLewis** [comment]
Again same major issue, after they visit the notification its not being cleared, and im having a lot of people complain about this.
Also the clear notifications should also be in the notifications dropdown.

**Comment by sbrajesh** [comment]
The clear notifications is not offered by BuddyPress, We do have a plugin bp-clear-notification that adds it in the admin menu.
The issue related to forum seems to be fixed now.

**Comment by TomLewis** [comment]
This was posted in 2013, **7 years ago**

**Comment by sbrajesh** [comment]
I am sorry about that. We are not using github for the issue management at the moment  and my reply was to update the topic status. Most of the issues opened on our repositories did not get proper replies due to this.
I just want to update it for any new users looking for the same.
