### ISSUE TITLE
does not notify new users joined a public group, does not notify favorites or likes on group activity stream

### ISSUE THREAD

**Issue by quinngoldwin** [sbrajesh/bp-group-activities-notifier#2]
1. doesnt notify new users joined a public group, 

2 doesnt notify favorites or likes on group activity stream

**Comment by sbrajesh** [comment]
Hi,
I am sorry i forgot to post the updated version on BuddyDev. Please download 1.0.1 from here
http://buddydev.com/plugins/bp-group-activities-notifier/
It does notify on new user join.

If you want to be notified of favorites/group comment notificatoion, please use bp activity comment notifier plugin from here

http://buddydev.com/plugins/buddypress-activity-comment-notifier/

Hope that helps.
