### ISSUE TITLE
Blank notifications problem

### ISSUE THREAD

**Issue by ArkGladios** [sbrajesh/bp-group-activities-notifier#3]
I'm using the last update of the plugin (12 July) but it shows continuously **blank notifications**.
These are some screenshot so you can understand better what I'm talking about:

<img width="557" alt="issue1" src="https://cloud.githubusercontent.com/assets/2293146/11015053/3f08d040-854f-11e5-943f-b07205c457af.png">

<img width="1138" alt="issue2" src="https://cloud.githubusercontent.com/assets/2293146/11015054/3f0a968c-854f-11e5-9038-d9ade34e403b.png">

**I'm using Buddypress 2.3.4**

**Comment by sbrajesh** [comment]
Hi,
My apologies for the issue. Can you please click on view and tell me what type of notification it is happening for? Is it happening for group activity or forums or something else?

**Comment by ArkGladios** [comment]
It's all related to group activity. I don't know what type of notification is, because there are only blank spaces. 

Analyzing with the Inspector, each blank notification has a link to a group activity, but when I follow that it returns me a 404. 

P.S.
When a new member join in a group I use to delete the join group activity from the stream; I was thinking that the blank notifications were related to this, but these notifications are more than the member that actually join. 
Just to give it a try, how can I deactivate the notifications for the members joining in groups?
Thanks!

**Comment by ArkGladios** [comment]
**update:** Perfect, I've tested also locally and now I can confirm that the problem **appears** when:
1. **USER 1** post a new activity or joins the group
2. **USER 2** receives the notification that notifiy him on the new activity of **USER 1** (**USER 1**'s new post or  join activity)
3. An **administrator**  _delete_ **USER 1**'s activity (his new post or his join activity) from the **Group Activity Stream**
4. Now, when **USER 2** checks the notification center, it will see a blank notification, because that activity has been deleted.

**Comment by sbrajesh** [comment]
Thank you for testing. Please try this

```
add_action( 'bp_init', 'buddydev_stop_group_join_activity' );

function buddydev_stop_group_join_activity() {
    if( has_action( 'groups_membership_accepted', 'bp_groups_membership_accepted_add_activity' ) ) {
        remove_action( 'groups_membership_accepted', 'bp_groups_membership_accepted_add_activity', 10, 2 );
    }
}
```

Putting that in bp-custom.php should disable the join activity.

**Comment by ArkGladios** [comment]
_Thanks for your time_ @sbrajesh 
Unfortunately the code you wrote didn't work for me, even if I put this in the functions file. 

However, I managed to stop the Join activities from being displayed in groups' stream with this code:

```
     // Stop NEW Join Activities
    function stop_save_join_group_activity( $activity_object ) {
    $exclude = array( 'joined_group' );

    if( in_array( $activity_object->type, $exclude ) )
    $activity_object->type = false;
    }
    add_action('bp_activity_before_save', 'stop_save_join_group_activity', 1, 1 );
```

P.S. You could improve your plugin making it be able to control If an activity is deleted and, if yes, deleting also the notification associated with the ID of the deleted activity. (Hope I've explained this well). 
Thanks
