### ISSUE TITLE
How to Stop sending notification for New User join in Group 

### ISSUE THREAD

**Issue by valarmurugan** [sbrajesh/bp-group-activities-notifier#4]
Thanks for the excellent work.. Your plugin adds interesting function / features to buddypress community.

Need to know "how to block the buddypress notification for New User join in Group"

Am using  - BP Group Activities Notifier

Can you share some snippet to place in function.php to achieve this

Thanks

**Comment by maxledoux** [comment]
@valarmurugan I got this snippet from @sbrajesh somewhere else (can't remember where, but all credit to him of course). Putting it here for reference.
```php
//Do not notify for join group activity in BP Local group Activity notifier
function buddydev_do_not_notify_join_group_activity( $stop_notification, $activity ) {
    if ( $activity->type == 'joined_group' ) {
       $stop_notification = true;
    }

    return $stop_notification;
}
add_filter( 'bp_local_group_notifier_skip_notification', 'buddydev_do_not_notify_join_group_activity', 10, 2 );
```
Put in `bp-custom.php`
