### ISSUE TITLE
Random spaces in the notifications 

### ISSUE THREAD

**Issue by TomLewis** [sbrajesh/bp-group-activities-notifier#5]
Here is a prime example of the 2 issues already reported, this is a report from one of my users about the way this plugin works.
User join notification needs to be changed, not disabled like in this https://github.com/sbrajesh/bp-group-activities-notifier/issues/4 but It needs to be changed.

Notifications are not clearing https://github.com/sbrajesh/bp-group-activities-notifier/issues/1

My additional issue is that there are random spaces just slapped into the notification window.
Look at this image from an average user on my site:

http://piratemc.com/wp-content/uploads/2016/12/Screenshot-2016-12-30-19.22.03.png

**Comment by sbrajesh** [comment]
Sorry for not seeing it earlier. This is dependent on theme and no on this plugin.
