### ISSUE TITLE
Link to group activity wall instead of user activity wall

### ISSUE THREAD

**Issue by StrothiP** [sbrajesh/bp-group-activities-notifier#8]
Dear @sbrajesh,

first of all thanks for the great plugin! Works really nice :) Now, when a user posts an activity in a group, others clicking on the activity notification will be redirected to that user's private activity wall. I was wondering whether it would be possible to redirect users instead to the respective group activity stream - which would make more sense in my mind?

Thanks so much in advance!

Kind regards, Philip

**Comment by sbrajesh** [comment]
I am sorry, I could not reply earlier. 
We do not redirect to either of the page. We link to single permalink of the activity. It is BuddyPress's job to decide where to show that activity.
