### ISSUE TITLE
How i can add notification list tab in the main admin panel

### ISSUE THREAD

**Issue by azharmehmood846** [sbrajesh/bp-group-activities-notifier#9]
This is a great effort. I just want to know one thing. how I can add notifications list and allow them for a different group from the admin panel.
I just want to add custom notifications for different groups in BuddyPress.
Thanks

**Comment by sbrajesh** [comment]
Please see BuddyPress template pack and bp_has_notifications(). This plugin does not offer the required functionality. You may be able to achieve that by copying and modifying the template code from default template packs.
